import { StyleSheet, Platform } from 'react-native';
import { Colors, Radius, Shadows, Spacing, Typography } from '@/shared/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FBF6EE',
  },
  keyboardAvoid: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xxxl,
  },
  // Top Row
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  stepBadge: {
    backgroundColor: '#EDE3D2',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: Radius.pill,
  },
  stepBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#7A6E5C',
    letterSpacing: 0.8,
  },
  lescoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3EADA',
    borderColor: '#EAE0D0',
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: Radius.pill,
    gap: 4,
  },
  lescoBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#B5551A',
  },

  // Titles
  titleBox: {
    marginBottom: Spacing.lg,
  },
  title: {
    fontSize: 32,
    fontWeight: '900',
    color: '#2B241C',
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: '#7A6E5C',
    fontWeight: '500',
  },

  // Form Fields
  row: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginBottom: Spacing.md,
  },
  halfField: {
    flex: 1,
  },
  fieldGroup: {
    marginBottom: Spacing.md,
  },
  label: {
    fontSize: 13,
    fontWeight: '800',
    color: '#2B241C',
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E8DFCE',
    borderRadius: 16,
    paddingHorizontal: Spacing.md,
    height: 50,
    fontSize: 14,
    color: '#2B241C',
    fontWeight: '500',
  },
  inputFocused: {
    borderColor: '#B5551A',
  },
  inputWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E8DFCE',
    borderRadius: 16,
    paddingHorizontal: Spacing.md,
    height: 50,
  },
  textInputInside: {
    flex: 1,
    fontSize: 14,
    color: '#2B241C',
    fontWeight: '500',
  },
  trailingIcon: {
    fontSize: 16,
    color: '#7A6E5C',
  },
  errorText: {
    fontSize: 11,
    color: '#C0392B',
    marginTop: 4,
    fontWeight: '600',
  },

  // Submit Button
  submitButton: {
    backgroundColor: '#B5551A',
    borderRadius: 16,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.md,
    shadowColor: '#B5551A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },

  // SOS Contact Box
  sosSection: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8DFCE',
    borderRadius: 16,
    padding: Spacing.md,
    marginBottom: Spacing.md,
    marginTop: Spacing.xs,
    shadowColor: '#2B241C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
    overflow: 'hidden',
  },
  sosHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
    gap: 8,
  },
  sosHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
    flexShrink: 1,
  },
  sosHeaderTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#B5551A',
    flexShrink: 1,
  },
  pickContactBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F3EADA',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: '#E8DFCE',
    flexShrink: 0,
  },
  pickContactBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#B5551A',
  },
  sosFieldGroup: {
    marginBottom: Spacing.xs + 2,
  },
  sosFieldLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2B241C',
    marginBottom: 4,
  },
  sosInput: {
    backgroundColor: '#FBF6EE',
    borderWidth: 1,
    borderColor: '#E8DFCE',
    borderRadius: 12,
    height: 42,
    paddingHorizontal: Spacing.md,
    fontSize: 14,
    color: '#2B241C',
  },
  relationChipsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  relationChip: {
    flex: 1,
    backgroundColor: '#FBF6EE',
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E8DFCE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  relationChipActive: {
    backgroundColor: '#B5551A',
    borderColor: '#B5551A',
  },
  relationChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#7A6E5C',
  },
  relationChipTextActive: {
    color: '#FFFFFF',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FBF6EE',
    paddingHorizontal: Spacing.md,
    paddingVertical: 9,
    borderRadius: 12,
    marginTop: Spacing.xs,
    borderWidth: 1,
    borderColor: '#E8DFCE',
  },
  checkboxLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#2B241C',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#C4B8A6',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxActive: {
    backgroundColor: '#B5551A',
    borderColor: '#B5551A',
  },
  checkIcon: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: Platform.OS === 'android' ? -2 : 0,
  },
});
