plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.lescohanddetector'
version = '0.1.0'

android {
  namespace "expo.modules.lescohanddetector"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
  aaptOptions {
    noCompress "task"
  }
  sourceSets {
    main {
      assets.srcDirs = ['src/main/assets']
    }
  }
}

dependencies {
  implementation 'com.google.mediapipe:tasks-vision:0.10.14'
}
